### ISSUE TITLE
Exposed Toke

### ISSUE THREAD

**Issue by basmoura** [IgorGoncalves/api-calouradas#1]
@IgorGoncalves esse token de autenticação deveria ser uma variável de ambiente e definida por quem vai implementar o calendário, não?

https://github.com/IgorGoncalves/api-calouradas/blob/457f7fc1864ecbedc2f749f939ef3d78b5a11515/app/Http/Controllers/AgendaController.php#L63

**Comment by igorgoncalves** [comment]
Hey @basmoura! Corrigi o problema, e o fato do arquivo de credentials estar no public/, agora está ok :D

Acabei usando XGH pra fazer a API do calendar funcionar e falhei na segurança, obrigado!

Você pode ver como está ficando por aqui: http://calouradas.igoncalves.tk/

https://github.com/IgorGoncalves/api-calouradas/blob/cfd6a019af29ccbf2c8e508f30aec5042a4879f2/app/Http/Controllers/AgendaController.php#L115
